# Generated by Django 2.0 on 2018-01-17 02:59

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('value', models.CharField(db_index=True, max_length=300)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='aces_pies_data.Attribute')),
            ],
            options={
                'ordering': ('value',),
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('short_name', models.CharField(db_index=True, max_length=10, unique=True)),
                ('marketing_copy', models.TextField(null=True)),
            ],
            options={
                'ordering': ('created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='aces_pies_data.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DigitalAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('url', models.CharField(max_length=200, unique=True)),
                ('file_size_bytes', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalAssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngineAspiration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=12)),
            ],
            options={
                'ordering': ('created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FuelDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('import_action', models.IntegerField(choices=[(1, 'Import'), (2, 'Archive'), (3, 'No Action')], db_index=True, default=1)),
                ('file_name', models.CharField(max_length=100)),
                ('stack_trace', models.TextField(null=True)),
                ('brand_short_name', models.CharField(db_index=True, max_length=10)),
                ('start_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('end_date', models.DateTimeField(db_index=True, null=True)),
            ],
            options={
                'ordering': ('created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportTrackingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'ordering': ('created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('part_number', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('is_hazardous', models.BooleanField(db_index=True, default=False)),
                ('is_carb_legal', models.BooleanField(db_index=True, default=True)),
                ('is_discontinued', models.BooleanField(db_index=True, default=False)),
                ('is_obsolete', models.BooleanField(db_index=True, default=False)),
                ('map_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=7, null=True)),
                ('retail_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=7, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aces_pies_data.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aces_pies_data.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aces_pies_data.Attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='aces_pies_data.Product')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aces_pies_data.AttributeValue')),
            ],
            options={
                'ordering': ('attribute__name', 'value__value'),
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('brand_short_name', models.CharField(db_index=True, max_length=10)),
                ('part_number', models.CharField(db_index=True, max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aces_pies_data.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDigitalAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('display_sequence', models.PositiveSmallIntegerField()),
                ('digital_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aces_pies_data.DigitalAsset')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_assets', to='aces_pies_data.Product')),
            ],
            options={
                'ordering': ('display_sequence',),
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=300)),
                ('listing_sequence', models.PositiveSmallIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='aces_pies_data.Product')),
            ],
            options={
                'ordering': ('listing_sequence',),
            },
        ),
        migrations.CreateModel(
            name='ProductFitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('start_year', models.PositiveSmallIntegerField(db_index=True)),
                ('end_year', models.PositiveSmallIntegerField(db_index=True)),
                ('fitment_info_1', models.CharField(max_length=1000, null=True)),
                ('fitment_info_2', models.CharField(max_length=1000, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitment', to='aces_pies_data.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPackaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('product_quantity', models.PositiveSmallIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('dimensional_weight', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('length', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='aces_pies_data.Product')),
            ],
            options={
                'ordering': ('created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('configuration', models.CharField(db_index=True, max_length=3)),
                ('liters', models.DecimalField(db_index=True, decimal_places=1, max_digits=3, null=True)),
                ('engine_code', models.CharField(db_index=True, max_length=100, null=True)),
                ('aspiration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engines', to='aces_pies_data.EngineAspiration')),
                ('fuel_delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engines', to='aces_pies_data.FuelDelivery')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engines', to='aces_pies_data.FuelType')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ('created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aces_pies_data.VehicleMake')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleSubModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aces_pies_data.VehicleModel')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('start_year', models.PositiveIntegerField(db_index=True)),
                ('end_year', models.PositiveIntegerField(db_index=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aces_pies_data.Vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aces_pies_data.VehicleEngine'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aces_pies_data.VehicleMake'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aces_pies_data.VehicleModel'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='sub_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aces_pies_data.VehicleSubModel'),
        ),
        migrations.AddField(
            model_name='productfitment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aces_pies_data.Vehicle'),
        ),
        migrations.AddField(
            model_name='importtracking',
            name='tracking_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracking_records', to='aces_pies_data.ImportTrackingType'),
        ),
        migrations.AddField(
            model_name='digitalasset',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aces_pies_data.DigitalAssetType'),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aces_pies_data.DigitalAsset'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='aces_pies_data.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicleyear',
            unique_together={('vehicle', 'start_year', 'end_year')},
        ),
        migrations.AlterUniqueTogether(
            name='vehiclesubmodel',
            unique_together={('name', 'model')},
        ),
        migrations.AlterUniqueTogether(
            name='vehiclemodel',
            unique_together={('name', 'make')},
        ),
        migrations.AlterUniqueTogether(
            name='vehicleengine',
            unique_together={('configuration', 'liters', 'fuel_type', 'fuel_delivery', 'aspiration', 'engine_code')},
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('make', 'model', 'sub_model', 'engine')},
        ),
        migrations.AlterUniqueTogether(
            name='productfitment',
            unique_together={('product', 'vehicle', 'start_year', 'end_year', 'fitment_info_1', 'fitment_info_2')},
        ),
        migrations.AlterUniqueTogether(
            name='productfeature',
            unique_together={('name', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='productdigitalasset',
            unique_together={('product', 'digital_asset')},
        ),
        migrations.AlterUniqueTogether(
            name='productcategorylookup',
            unique_together={('brand_short_name', 'category', 'part_number')},
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('product', 'attribute', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('part_number', 'brand')},
        ),
        migrations.AlterUniqueTogether(
            name='digitalasset',
            unique_together={('url', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('attribute', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('name', 'category')},
        ),
    ]
