# Generated by Django 2.0.2 on 2018-02-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aces_pies_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_superseded',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='superseded_by',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
    ]
